### ISSUE TITLE
Failed to load connection info: "TimeoutError: Timed out after 5s"

### ISSUE THREAD

**Issue by seanmcnally98** [bitfocus/companion-module-generic-tcp-udp#16]
For some reason, when moving my config to a new machine, two of my connections were glitched - with the error Failed to load connection info: "TimeoutError: Timed out after 5s".  I cannot get into those to configure them, I suppose I'll need to just delete those connections and replace them with new ones.

**Comment by istnv** [comment]
Recent updates should allow the configuration tab to load instead of being locked in the error state.
