### ISSUE TITLE
Hexadecimal command encoding issue in tcp-udp module

### ISSUE THREAD

**Issue by Florent-ARENE** [bitfocus/companion-module-generic-tcp-udp#24]
Hello,

I am encountering an issue with the tcp-udp module in Companion when sending hexadecimal commands to my Sony SRG-300SE camera. The sent commands are altered, likely due to an encoding issue.

Here is the observed behavior:

When I send a command like \x81\x01\x04\x3F\x02\x02\xFF via Companion, the camera does not react as expected.
Using Wireshark, I noticed that the sent commands are modified. For example, \x81 becomes \xFD and \xFF becomes \xFD.
Researching a solution, I found that the problem is related to UTF-16 encoding. It seems the commands are re-encoded, which alters the bytes.
To work around this issue, I had to use Latin1 encoding in other contexts to avoid these alterations. Could you add an option to force Latin1 encoding in the tcp-udp module of Companion to ensure that hexadecimal commands are transmitted without modification?

Thank you in advance for your help!

**Comment by istnv** [comment]
What version of companion? This was addressed a couple of weeks ago and is in the current Beta release.

**Comment by Florent-ARENE** [comment]
Thank you for your quick response. Indeed, after checking, I found that the issue has been resolved in the current beta release of Companion. I updated to this version, and now everything works perfectly.

I apologize for not finding the answer in the resolved issues earlier.

Thank you again for your help!
