### ISSUE TITLE
Issue parsing/encoding commands

### ISSUE THREAD

**Issue by studiotechnick** [bitfocus/companion-module-generic-tcp-udp#3]
I am testing the viability of a protocol with the Companion app, so I am using the Generic UDP sender. I am attempting to send a number of hex values, but the command is either not being parsed correctly, or is getting encoded in some way. For example:

I am sending:
%ff%ff%00%1e%07%e1%00%00%90%b1%1c%5b%d2%85%00%00%53%74%75%64%69%6f%2d%54%5a%16%02%00%01%04

Which yields:
%c3%bf%c3%bf%00%1e%07%c3%a1%00%00%c2%90%c2%b1%1c%5b%c3%92%c2%85%00%00%53%74%75%64%69%6f%2d%54%5a%16%02%00%01%04

More bytes are added to the data section of the message. When I send %00%01%02, I get %00%01%02. But when I send values where the MSB is 1, things get weird. Sending %ff yields %c3%bf (which can be seen in the example above). Sending %9f yields %c2%9f.

**Comment by istnv** [comment]
Pull request #2  will fix this. Waiting for someone to merge into core.

**Comment by McHauge** [comment]
@istnv merged, now we just need a core dev to update it to the core

**Comment by istnv** [comment]
@McHauge Thanks

**Comment by studiotechnick** [comment]
Awesome thanks!
