### ISSUE TITLE
UDP recurrence request.

### ISSUE THREAD

**Issue by Boguinhos** [bitfocus/companion-module-generic-tcp-udp#4]
Hi guys!! Is there any way to make that this udp request repeats itself from time to time, since the action was called? Like a keep alive, with a user input refresh value.

Thank you!

**Comment by JeffreyDavidsz** [comment]
Looks like you need a module created... Meanwhile look at the scheduler

**Comment by Boguinhos** [comment]
thanks for the scheduler tip. will look for wtver that is :D 

Yeah maybe what i need does not really match up to what companion does. but it's sort of almost ....

**Comment by istnv** [comment]
You could also try a self-repeating button:
Action 1: Send UDP packet
Action 2: (5000ms delay) Push this button again
