### ISSUE TITLE
TCP recieve data to Companion buttons with feedback (colour/text) - Budget available for update - 1 week timeline 

### ISSUE THREAD

**Issue by jcuthbertson** [bitfocus/companion-module-generic-tcp-udp#5]
I am aware this is a very generic module.  I am hoping fo the developers implement the following.  I have a budget for modifications, I am hoping to have this complete within 1 week.

Currently, the module is set up to send TCP commands to generic devices.  I would like to send button feedback back to Companion that controls button colour and text via TCP to targeted buttons.

I am using justmacros in this case, I have posted in the justmacros github a module update request.  I have spoken with the original developer and we wasn't sure if it was possible from his end.  The reality is this module would be a better fit if someone is willing to do modify it because many others would likely be able to use the modifications.  

As I mentioned I have a budget for this update and ideally it is completed within 1 week.

Thanks
Jon Cuthbertson

**Comment by lbennexigo** [comment]
I love this module!!! I'm writing commands directly to a Siemens s7-1200 PLC, works great!!! It would be amazing to have feedback to the control buttons, please please please add this feature.

**Comment by JeffreyDavidsz** [comment]
Just to be clear, the request is to control button colors and button text? I believe button text is already an option, not sure about colors though
